[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
mint-nft-standard = "dC9AHAGp4pRXgLDM3Y9mXfbcTFJhvcJS7J4fXC4nEzy"
mint_nft = "FuXM8HFaNujkovGhJVPYJxbRG6DaMjdYEV9VaC8N4K8i"
nft-2022 = "CfWK53q7cVf3vNj6K6BfqmnUVKo1uDGFXujR9fKV7dd6"
test-program = "73mDoPfiVb7MJtXchdzteB1APVzzzMHKYdrSU7R93B5S"
transfer-hook = "fHvRUSXf2mpFMpcaZJifJuCHWQcrsDSC91cdqx8echQ"

[programs.localnet]
mint-nft-standard = "dC9AHAGp4pRXgLDM3Y9mXfbcTFJhvcJS7J4fXC4nEzy"
mint_nft = "FuXM8HFaNujkovGhJVPYJxbRG6DaMjdYEV9VaC8N4K8i"
test-program = "73mDoPfiVb7MJtXchdzteB1APVzzzMHKYdrSU7R93B5S"
transfer-hook = "fHvRUSXf2mpFMpcaZJifJuCHWQcrsDSC91cdqx8echQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/Documents/code/program-examples/tokens/nft-operations/anchor/solflare-wallet-keypair.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
